export const FETCH_WEATHER_DATA = 'FETCH_WEATHER_DATA';

export const SEARCH_COUNTRY_START = 'SEARCH_COUNTRY_START';
export const SEARCH_COUNTRY_SUCCESS = 'SEARCH_COUNTRY_SUCCESS';
export const SEARCH_COUNTRY_FAILURE = 'SEARCH_COUNTRY_FAILURE';
